In [1]:
import pandas as pd
import numpy as np

In [4]:
raw_us = pd.read_csv("../resources/us-maps/us-state-counties.tsv", sep="\t")
raw_us.iloc[0]

state            Alabama
county    Autauga County
lat              32.5322
lon             -86.6464
Name: 0, dtype: object

In [9]:
us = pd.DataFrame(index=raw_us.index)
us["country"] = "United States"
us["stateprovince"] = raw_us["state"]
us["county"] = raw_us["county"]
us.head()

         country stateprovince          county
0  United States       Alabama  Autauga County
1  United States       Alabama  Baldwin County
2  United States       Alabama  Barbour County
3  United States       Alabama     Bibb County
4  United States       Alabama   Blount County

In [14]:
df = us.copy()
df["kingdom"] = "plantae"
df["phylum"] = "tracheophyta"
df["family"] = "sapindaceae"
df["genus"] = "acer"
df["specificepithet"] = "saccharum"
sugarmaple = df
sugarmaple.head()

,country,stateprovince,county,kingdom,phylum,family,genus,specificepithet
0,United States,Alabama,Autauga County,plantae,tracheophyta,sapindaceae,acer,saccharum
1,United States,Alabama,Baldwin County,plantae,tracheophyta,sapindaceae,acer,saccharum
2,United States,Alabama,Barbour County,plantae,tracheophyta,sapindaceae,acer,saccharum
3,United States,Alabama,Bibb County,plantae,tracheophyta,sapindaceae,acer,saccharum
4,United States,Alabama,Blount County,plantae,tracheophyta,sapindaceae,acer,saccharum

In [15]:
df = us.copy()
df["kingdom"] = "plantae"
df["phylum"] = "tracheophyta"
df["family"] = "fabaceae"
df["genus"] = "amorpha"
df["specificepithet"] = "canescens"
leadplant = df
leadplant.head()

,country,stateprovince,county,kingdom,phylum,family,genus,specificepithet
0,United States,Alabama,Autauga County,plantae,tracheophyta,fabaceae,amorpha,canescens
1,United States,Alabama,Baldwin County,plantae,tracheophyta,fabaceae,amorpha,canescens
2,United States,Alabama,Barbour County,plantae,tracheophyta,fabaceae,amorpha,canescens
3,United States,Alabama,Bibb County,plantae,tracheophyta,fabaceae,amorpha,canescens
4,United States,Alabama,Blount County,plantae,tracheophyta,fabaceae,amorpha,canescens

In [16]:
df = us.copy()
df["kingdom"] = "animalia"
df["phylum"] = "chordata"
df["family"] = "dasypodidae"
df["genus"] = "dasypus"
df["specificepithet"] = "novemcinctus"
armadillo = df
armadillo.head()

,country,stateprovince,county,kingdom,phylum,family,genus,specificepithet
0,United States,Alabama,Autauga County,animalia,chordata,dasypodidae,dasypus,novemcinctus
1,United States,Alabama,Baldwin County,animalia,chordata,dasypodidae,dasypus,novemcinctus
2,United States,Alabama,Barbour County,animalia,chordata,dasypodidae,dasypus,novemcinctus
3,United States,Alabama,Bibb County,animalia,chordata,dasypodidae,dasypus,novemcinctus
4,United States,Alabama,Blount County,animalia,chordata,dasypodidae,dasypus,novemcinctus

In [17]:
df = us.copy()
df["kingdom"] = "animalia"
df["phylum"] = "chordata"
df["family"] = "picidae"
df["genus"] = "leuconotopicus"
df["specificepithet"] = "albolarvatus"
woodpecker = df
woodpecker.head()

,country,stateprovince,county,kingdom,phylum,family,genus,specificepithet
0,United States,Alabama,Autauga County,animalia,chordata,picidae,leuconotopicus,albolarvatus
1,United States,Alabama,Baldwin County,animalia,chordata,picidae,leuconotopicus,albolarvatus
2,United States,Alabama,Barbour County,animalia,chordata,picidae,leuconotopicus,albolarvatus
3,United States,Alabama,Bibb County,animalia,chordata,picidae,leuconotopicus,albolarvatus
4,United States,Alabama,Blount County,animalia,chordata,picidae,leuconotopicus,albolarvatus

In [23]:
pd.concat([sugarmaple, leadplant, armadillo, woodpecker]).to_csv("../results/us-maps/all.tsv", sep="\t", index=False)